# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitBackened', '0003_auto_20160716_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
