# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitBackened', '0004_event_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='score',
            new_name='Score',
        ),
    ]
