# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waitBackened', '0005_auto_20160716_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.TimeField(default=datetime.datetime(2016, 7, 16, 8, 19, 44, 792501, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='NoImages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
